### ISSUE TITLE
Testes Unitários Produtos

### ISSUE THREAD

**Issue by murilomontino** [murilomontino/FUNCAP.FuncapFlix-NextJs#50]
- [x] Testes Unitários de: #33
- [ ] Testes Unitários de: #34
- [ ] Testes Unitários de: #35
- [ ] Testes Unitários de: #36
- [ ] Testes Unitários de: #37
- [ ] Testes Unitários de: #38
- [ ] Testes Unitários de: #45
